Step1
kiworkshop/java-chess pull request #13
Opened 2021-08-24 13:32 UTC by pageprologue

## 학습로그
   1. [정적 팩토리 메서드](https://velog.io/@bosl95/%EC%9E%90%EB%B0%94%EC%9D%98-Static-Factory-Method )
   2. [Stream 매핑 사용법](https://cornswrold.tistory.com/297)
   3. [Optional 제대로 활용하기](https://www.latera.kr/blog/2019-07-02-effective-optional)

2021-09-01 00:05 UTC, me0768 requested changes
희진선생님. 코드리뷰가 많이 늦었네요 ㅠㅠ
여기까지 구현하면서 고민 많이 하셨을텐데 수고하셨습니다
몇가지 코멘트 남겼으니 확인부탁드립니다 :)

2021-09-01 00:05 UTC, myangw commented on src/main/java/chess/controller/ChessGameController.java
> +        OutputView.printWinner(winner);
게임이 끝나면 우승자의 기물 뿐만아니라 우승자가 흑인지 백인지, Score가 몇이었는지를 함께 보여줘야할 것 같은데 이 부분이 빠져있습니다

2021-09-01 00:05 UTC, myangw commented on src/main/java/chess/domain/piece/Bishop.java
> +    public boolean moveStrategy(Position source, Position target) {
boolean을 리턴하는걸 고려해서 좀더 적절한 네이밍을 생각해보시면 좋겠습니다.

2021-09-01 00:05 UTC, myangw commented on src/main/java/chess/domain/piece/Blank.java
> +        return false;
canMove 메서드를 `source.canMove(board, source, target)` 과 같이 쓰시는데요,
Blank일때는 비어있는 상태를 target으로 옮기는 행위를 하진 못하므로 이부분은 로직 없이 false를 리턴해야할거같습니다.

그리고 source 인스턴스의 메서드를 실행하면서 source 자체를 또 파라미터로 넘겨줄 필요 없을 것 같아요. source 그 자체이기 때문에 `this.team()` 과 같이 쓸 수 있을거에요

2021-09-01 00:05 UTC, myangw commented on src/main/java/chess/domain/piece/Knight.java
> +        return movablePositions.contains(target.position());
26, 27번째 줄이 거의 모든 Piece에서 사용되는 로직이라 이부분도 묶어서 메서드로 만들어두고 쓰면 중복이 줄어들거같아요.

List의 contains를 쓰는 것 말고 좀더 효율적으로 개선도 가능해보입니다.

2021-09-01 00:05 UTC, myangw commented on src/main/java/chess/domain/view/InputView.java
> +    private static final Pattern pattern = Pattern.compile("move [a-h]{1}[1-8]{1} [a-h]{1}[1-8]{1}");
여기서 정규표현식 쓰신 시도 좋네요 :)

2021-09-01 00:05 UTC, myangw commented on src/main/java/chess/game/Score.java
> +        return (sum - (sameFileCount * PAWN_SAME_FILE_SCORE)) * kingCount;
`PAWN_SAME_FILE_SCORE` 가 Score에서만 쓰이고 있는데 Score로 옮기면 어떨까요

2021-09-01 00:05 UTC, myangw commented on src/main/java/chess/game/Score.java
> +    private static int isSameFile(List<Piece> pieces) {
메서드 명에 **'Pawn이' 같은 세로줄에 있는 '개수'** 를 나타내면  calculateSum 메서드에서 명확하게 읽힐 것 같습니다.

2021-09-01 00:05 UTC, myangw commented on src/test/java/chess/domain/game/ChessGameTest.java
> +class ChessGameTest {
짜놓으신 테스트 전체를 돌려봤는데 5개는 실패합니다. 

근데 테스트가 129개나... 👏 👏

2021-09-01 00:05 UTC, myangw commented on src/main/java/chess/domain/piece/Pawn.java
> +        return (Math.abs(source.fileNumber() - target.fileNumber()) == 1) && (source.rankNumber() - target.rankNumber() == 1);
target이 Blank인지 아닌지에 대해서도 함께 체크해줘야 하지 않을까요? 단순 이동이라면 대각선으로 못움직여야 하는데 그 부분에 대한 내용을 못찾았습니다
(target이 Blank-> 공격 아닌 이동
target이 Blank가 아님 -> 공격)

2021-09-01 00:05 UTC, myangw commented on src/main/java/chess/domain/movement/Movement.java
> +        pieces.forEach(piece -> disableJump(piece));
knight를 제외하고 모두 다른 기물을 넘을 수 없는데, Pawn과 King에서는 이 메서드를 사용하지 않고 있습니다.

+)
이 메서드의 역할이 보드 안에 기물들 중에서 jump하려는데가 없는지 체크 하는 메서드로 이해했는데
`disableJump`라는 네이밍을 봤을 때는 'Jump를 할 수 있었는데 못하게 하다'의 느낌이어서 읽으면서 좀 혼동되었습니다.  `notTryingJump` 라던지 이 메서드가 호출되는 부분의 흐름 상에도 잘 읽히게 하면 좋겠어요

2021-09-01 00:05 UTC, me0768 commented on src/main/java/chess/game/Score.java
> +                .collect(groupingBy(pawn -> pawn.position().fileNumber(), counting()));
stream으로 이렇게 counting할수있군요. 👍

2021-09-16 11:21 UTC, pageprologue commented on src/main/java/chess/controller/ChessGameController.java
> +        OutputView.printWinner(winner);
넵 점수도 출력하도록 수정하였습니다~!

2021-09-16 11:27 UTC, pageprologue commented on src/main/java/chess/domain/piece/Bishop.java
> +    public boolean moveStrategy(Position source, Position target) {
이 부분은 체스 말의 이동 규칙에 대한 역할을 클래스로 빼서 설계가 많이 변경되었습니다. 체스 말 이동 규칙에 대해서 다시 한번 리뷰 부탁드리겠습니다~🙏

2021-09-16 11:34 UTC, pageprologue commented on src/main/java/chess/domain/piece/Blank.java
> +        return false;
Blank일 때 해당 위치에 체스말이 없다는 에러 메시지를 출력하기 위해 checkBlankPosition 메소드만 포함하도록 수정하였습니다.

2021-09-16 11:35 UTC, pageprologue commented on src/test/java/chess/domain/game/ChessGameTest.java
> +class ChessGameTest {
실패하는 테스트 수정하였습니다!

2021-09-16 12:04 UTC, pageprologue commented on src/main/java/chess/domain/piece/Knight.java
> +        return movablePositions.contains(target.position());
이동 가능한 체스 말인지 검사하는 부분은 중복을 제거하였습니다.

contains 를 사용한 이유는, 기존 요구사항에는 없지만 웹에서 해당 체스말이 이동할 수 있는 위치를 표출하고 싶어서 이동 가능한 모든 위치를 List에 담도록 하였습니다. 
이동 가능한 모든 위치를 반환하는 getMovablePositions 메소드를 canMove 메소드에서 분리할 수는 있을 것 같은데요. 그래도 canMove 에서는 contains 로 확인해야 할 것 같습니다. 혹시 더 좋은 방향이 있을까요~?

2021-09-16 12:06 UTC, pageprologue commented on src/main/java/chess/game/Score.java
> +        return (sum - (sameFileCount * PAWN_SAME_FILE_SCORE)) * kingCount;
넵 Score로 옮겼습니다~!

2021-09-16 12:14 UTC, pageprologue commented on src/main/java/chess/game/Score.java
> +    private static int isSameFile(List<Piece> pieces) {
isSameFile 에서 pawnSameFileCount 으로 메서드명 수정하였습니다~!

2021-09-16 12:18 UTC, pageprologue commented on src/main/java/chess/domain/piece/Pawn.java
> +        return (Math.abs(source.fileNumber() - target.fileNumber()) == 1) && (source.rankNumber() - target.rankNumber() == 1);
이 부분은 폰 이동 규칙에서 getAttackPositions 에서 확인할 수 있도록 수정하였습니다~:)

2021-09-16 12:25 UTC, pageprologue commented on src/main/java/chess/domain/movement/Movement.java
> +        pieces.forEach(piece -> disableJump(piece));
폰과 킹은 1칸 씩 밖에 이동할 수 없기 때문에 (폰이 초기에 이동하는 경우에는 2칸도 가능하지만, 뛰어넘을 기물이 없음) disableJump 메서드가 빠져있었던 것 같습니다.
이 부분은 disableJump 메서드를 제거하고, 여러 칸을 이동할 수 있는 체스말의 이동 규칙에서 상대편 체스말이 있는 경우 더 이상 이동하지 못하도록 수정하였습니다.

2021-09-30 14:49 UTC, me0768 commented on src/main/java/chess/domain/piece/Knight.java
> +        return movablePositions.contains(target.position());
contains 관련은 Set을 쓰면 더 효율적일거라 생각했었는데, 지금 보면 어차피 List에 들어갈 원소 개수가 많지않아서 제가 오버한 감이 있습니다^^;;  게다가 이번 코드에서 Set의 contains를 쓰도록 바꾸셔서 넘어가시면 될거같습니다 (`Collections.toSet()`을 쓰면 기본적으로 구현체가 HashSet이고, 시간복잡도가 O(1)이라 arraylist의 O(n)보다 빠르다는 게 생각나 적었던 코멘트입니다)

2021-10-01 14:25 UTC, me0768 commented on src/main/java/chess/domain/movement/MoveStrategy.java
> +                .collect(Collectors.toSet());
음 상당히 복잡한데..
 takeWhile, dropWhile 둘 다 써야했던이유가 있을까요??  limit(1)을 하신걸 보면 이 둘을 합쳐서
```java
getPositionStream(direction, source)
.findFirst(board.isOtherTeam(source, target))
```
으로 하고 리턴타입을 Optional<Position>으로 해도 되겠단 생각을 했는데, 이렇게 하면 의도하신대로 안되려나용..

2021-10-02 02:48 UTC, pageprologue commented on src/main/java/chess/domain/piece/Knight.java
> +        return movablePositions.contains(target.position());
아하 그렇군요! 앞으로 시간복잡도에 대해서 좀 더 공부하고 고려해보록 하겠습니다~ 감사합니다 :)

2021-10-02 03:04 UTC, pageprologue commented on src/main/java/chess/domain/movement/MoveStrategy.java
> +                .collect(Collectors.toSet());
이 부분은 이동하려는 direction의 위치가 이동 가능한 위치인지 확인하는 부분인데요. 
takeWhile 은 상대편 체스말인 경우에 1개만 포함시키고
dropWhile 은 같은팀 체스말인 경우에는 포함시키지 않도록 하기 위해 이렇게 작성하였습니다.

2021-10-04 13:53 UTC, merged